# Generated by Django 2.2.7 on 2019-11-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujian_aplikasi_1174043', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
